services:
  - type: web
    name: lovejoy-antiques
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: lovejoy_kdwp
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: RECAPTCHA_PUBLIC_KEY
        value: 6LeZHI4qAAAAAHJG1aDnSd7D5G8hbCclDTEUMooN
      - key: RECAPTCHA_PRIVATE_KEY
        value: 6LeZHI4qAAAAAHBGr9x1EBhNguxHjCPYVePUzBGc
      - key: SERVER_NAME
        value: lovejoy.xiong71.xyz

databases:
  - name: lovejoy_kdwp
    databaseName: lovejoy_kdwp
    user: lovejoy_kdwp_user
    plan: free
