services:
  - type: web
    name: lovejoy-antiques
    env: python
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      source .venv/bin/activate
      flask db upgrade
      gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://lovejoy_kdwp_user:3Zg7hPC8KXcfIvc1QhJcVLJaAqBfXvtS@dpg-ct70ccrv2p9s739mum6g-a.oregon-postgres.render.com:5432/lovejoy_kdwp
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: RECAPTCHA_PUBLIC_KEY
        value: 6LeZHI4qAAAAAHJG1aDnSd7D5G8hbCclDTEUMooN
      - key: RECAPTCHA_PRIVATE_KEY
        value: 6LeZHI4qAAAAAHBGr9x1EBhNguxHjCPYVePUzBGc
      - key: SERVER_NAME
        value: lovejoy.xiong71.xyz

databases:
  - name: lovejoy_kdwp
    databaseName: lovejoy_kdwp
    user: lovejoy_kdwp_user
    plan: free
