services:
  - type: web
    name: lovejoy-antiques
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    disk:
      name: uploads
      mountPath: /opt/render/project/src/app/static/uploads
      sizeGB: 1
